print("true and true");
print("true & & false");
print("false & & false");
print("------------------");
print("true | | true");
print("true | | false");
print("false | | false");
print("------------------");
print("!true");
print("!false");